etcd = ["127.0.0.1:2379"]
[mysql]
    addr = "127.0.0.1:3306"
    user = "root"
    password = "root"
    dbName = "idserver"
    parameters = "charset=utf8&parseTime=True&loc=Local"
    maxConn = 20
    idleConn = 10
    idleTimeout = 14400000
    queryTimeout = 800
    execTimeout = 800
[log]
    logFileDir = "logs"
    appName = "idserver"
    maxSize = 100
    maxBackups = 60
    maxAge = 30
    level = "debug"
[server]
    addr = "127.0.0.1:8089"